### ISSUE TITLE
Introduction of raster extent 

### ISSUE THREAD

**Issue by tomalrussell** [datacarpentry/organization-geospatial#77]
This is a minor suggestion about how raster extent is introduced, in https://datacarpentry.org/organization-geospatial/01-intro-raster-data/index.html#extent

The image introduces point, line and polygon examples or R spatial objects as having extents - I wonder if the lesson could avoid introducing vector objects at this point? They will be introduced in the next episode. 

Instead, the example could show the extent of some raster data - perhaps a single satellite image tile, perhaps overlaid on an outline background map to show the geographical context (coastline or admin boundary) - something like [this image](https://scitools.org.uk/cartopy/docs/latest/_images/advanced_plotting-2.png) from https://scitools.org.uk/cartopy/docs/latest/matplotlib/advanced_plotting.html#images

**Comment by PennMGIS** [comment]
Thank you for this sensible suggestion. Introducing vector objects at this stage while the discussion is about raster extent undermines the flow of the lesson. The explanation also gets confusing since technically there is a slight difference between definitions of vector and raster extents. I also like the idea of providing an image extent example overlaid on an outline background map. The Xmin.Ymin & Xmax,Ymax  coordinates (used to define a raster extent) can also be shown as in this example https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/dev-aten/graphics/raster-general/sat_image_corners.png

**Comment by misgna3** [comment]
Thank you for this sensible suggestion. Introducing vector objects at this stage while the discussion is about raster extent undermines the flow of the lesson. The explanation also gets confusing since technically there is a slight difference between definitions of vector and raster extents. I also like the idea of providing an image extent example overlaid on an outline background map. The Xmin.Ymin & Xmax,Ymax coordinates (used to define a raster extent) can also be shown as in this example https://raw.githubusercontent.com/NEONScience/NEON-Data-Skills/dev-aten/graphics/raster-general/sat_image_corners.png
